rule "DEV door numbers":
    @Disabled
    
    #createInWorldText(getAllPlayers(), "1-2", Vectordoorpositions[0], 1, Clip.NONE, WorldTextReeval.VISIBILITY_POSITION_AND_STRING)
    #createInWorldText(getAllPlayers(), "3-4", Vectordoorpositions[1], 1, Clip.NONE, WorldTextReeval.VISIBILITY_POSITION_AND_STRING)
    #createInWorldText(getAllPlayers(), "5-6", Vectordoorpositions[2], 1, Clip.NONE, WorldTextReeval.VISIBILITY_POSITION_AND_STRING)
    #createInWorldText(getAllPlayers(), "7-8", Vectordoorpositions[3], 1, Clip.NONE, WorldTextReeval.VISIBILITY_POSITION_AND_STRING)
    #createInWorldText(getAllPlayers(), "9-10", Vectordoorpositions[4], 1, Clip.NONE, WorldTextReeval.VISIBILITY_POSITION_AND_STRING)
    #createInWorldText(getAllPlayers(), "11-12", Vectordoorpositions[5], 1, Clip.NONE, WorldTextReeval.VISIBILITY_POSITION_AND_STRING)
    #createInWorldText(getAllPlayers(), "13-14", Vectordoorpositions[6], 1, Clip.NONE, WorldTextReeval.VISIBILITY_POSITION_AND_STRING)
    #createInWorldText(getAllPlayers(), "15-16", Vectordoorpositions[7], 1, Clip.NONE, WorldTextReeval.VISIBILITY_POSITION_AND_STRING)
    #createInWorldText(getAllPlayers(), "17-18", Vectordoorpositions[8], 1, Clip.NONE, WorldTextReeval.VISIBILITY_POSITION_AND_STRING)
    #createInWorldText(getAllPlayers(), "19-20", Vectordoorpositions[9], 1, Clip.NONE, WorldTextReeval.VISIBILITY_POSITION_AND_STRING)
    #createInWorldText(getAllPlayers(), "21-22", Vectordoorpositions[10], 1, Clip.NONE, WorldTextReeval.VISIBILITY_POSITION_AND_STRING)
    #createInWorldText(getAllPlayers(), "23-24", Vectordoorpositions[11], 1, Clip.NONE, WorldTextReeval.VISIBILITY_POSITION_AND_STRING)
    #createInWorldText(getAllPlayers(), "25-26", Vectordoorpositions[12], 1, Clip.NONE, WorldTextReeval.VISIBILITY_POSITION_AND_STRING)
    #createInWorldText(getAllPlayers(), "27-28", Vectordoorpositions[13], 1, Clip.NONE, WorldTextReeval.VISIBILITY_POSITION_AND_STRING)
    #createInWorldText(getAllPlayers(), "29-30", Vectordoorpositions[14], 1, Clip.NONE, WorldTextReeval.VISIBILITY_POSITION_AND_STRING)
    #createInWorldText(getAllPlayers(), "31-32", Vectordoorpositions[15], 1, Clip.NONE, WorldTextReeval.VISIBILITY_POSITION_AND_STRING)
    #createInWorldText(getAllPlayers(), "33-34", Vectordoorpositions[16], 1, Clip.NONE, WorldTextReeval.VISIBILITY_POSITION_AND_STRING)
    #createInWorldText(getAllPlayers(), "35-36", Vectordoorpositions[17], 1, Clip.NONE, WorldTextReeval.VISIBILITY_POSITION_AND_STRING)
    #createInWorldText(getAllPlayers(), "37-38", Vectordoorpositions[18], 1, Clip.NONE, WorldTextReeval.VISIBILITY_POSITION_AND_STRING)
    #createInWorldText(getAllPlayers(), "39-40", Vectordoorpositions[19], 1, Clip.NONE, WorldTextReeval.VISIBILITY_POSITION_AND_STRING)
    #createInWorldText(getAllPlayers(), "41-42", Vectordoorpositions[20], 1, Clip.NONE, WorldTextReeval.VISIBILITY_POSITION_AND_STRING)
    #createInWorldText(getAllPlayers(), "43-44", Vectordoorpositions[21], 1, Clip.NONE, WorldTextReeval.VISIBILITY_POSITION_AND_STRING)
    #createInWorldText(getAllPlayers(), "45-46", Vectordoorpositions[22], 1, Clip.NONE, WorldTextReeval.VISIBILITY_POSITION_AND_STRING)
    #createInWorldText(getAllPlayers(), "47-48", Vectordoorpositions[23], 1, Clip.NONE, WorldTextReeval.VISIBILITY_POSITION_AND_STRING)
    #createInWorldText(getAllPlayers(), "49-50", Vectordoorpositions[24], 1, Clip.NONE, WorldTextReeval.VISIBILITY_POSITION_AND_STRING)
    #createInWorldText(getAllPlayers(), "51-52", Vectordoorpositions[25], 1, Clip.NONE, WorldTextReeval.VISIBILITY_POSITION_AND_STRING)
    #createInWorldText(getAllPlayers(), "53-54", Vectordoorpositions[26], 1, Clip.NONE, WorldTextReeval.VISIBILITY_POSITION_AND_STRING)
    #createInWorldText(getAllPlayers(), "55-56", Vectordoorpositions[27], 1, Clip.NONE, WorldTextReeval.VISIBILITY_POSITION_AND_STRING)
    #createInWorldText(getAllPlayers(), "57-58", Vectordoorpositions[28], 1, Clip.NONE, WorldTextReeval.VISIBILITY_POSITION_AND_STRING)
    #createInWorldText(getAllPlayers(), "59-60", Vectordoorpositions[29], 1, Clip.NONE, WorldTextReeval.VISIBILITY_POSITION_AND_STRING)
    #createInWorldText(getAllPlayers(), "61-62", Vectordoorpositions[30], 1, Clip.NONE, WorldTextReeval.VISIBILITY_POSITION_AND_STRING)
    #createInWorldText(getAllPlayers(), "63-64", Vectordoorpositions[31], 1, Clip.NONE, WorldTextReeval.VISIBILITY_POSITION_AND_STRING)
    #createInWorldText(getAllPlayers(), "65-66", Vectordoorpositions[32], 1, Clip.NONE, WorldTextReeval.VISIBILITY_POSITION_AND_STRING)
    #createInWorldText(getAllPlayers(), "67-68", Vectordoorpositions[33], 1, Clip.NONE, WorldTextReeval.VISIBILITY_POSITION_AND_STRING)
    #createInWorldText(getAllPlayers(), "69-70", Vectordoorpositions[34], 1, Clip.NONE, WorldTextReeval.VISIBILITY_POSITION_AND_STRING)
    #createInWorldText(getAllPlayers(), "71-72", Vectordoorpositions[35], 1, Clip.NONE, WorldTextReeval.VISIBILITY_POSITION_AND_STRING)
    #createInWorldText(getAllPlayers(), "73-74", Vectordoorpositions[36], 1, Clip.NONE, WorldTextReeval.VISIBILITY_POSITION_AND_STRING)
    #createInWorldText(getAllPlayers(), "75-76", Vectordoorpositions[37], 1, Clip.NONE, WorldTextReeval.VISIBILITY_POSITION_AND_STRING)
    #createInWorldText(getAllPlayers(), "77-78", Vectordoorpositions[38], 1, Clip.NONE, WorldTextReeval.VISIBILITY_POSITION_AND_STRING)
    #createInWorldText(getAllPlayers(), "79-80", Vectordoorpositions[39], 1, Clip.NONE, WorldTextReeval.VISIBILITY_POSITION_AND_STRING)
    #createInWorldText(getAllPlayers(), "81-82", Vectordoorpositions[40], 1, Clip.NONE, WorldTextReeval.VISIBILITY_POSITION_AND_STRING)
    #createInWorldText(getAllPlayers(), "83-84", Vectordoorpositions[41], 1, Clip.NONE, WorldTextReeval.VISIBILITY_POSITION_AND_STRING)
    #createInWorldText(getAllPlayers(), "85-86", Vectordoorpositions[42], 1, Clip.NONE, WorldTextReeval.VISIBILITY_POSITION_AND_STRING)
    #createInWorldText(getAllPlayers(), "87-88", Vectordoorpositions[43], 1, Clip.NONE, WorldTextReeval.VISIBILITY_POSITION_AND_STRING)
    #createInWorldText(getAllPlayers(), "89-90", Vectordoorpositions[44], 1, Clip.NONE, WorldTextReeval.VISIBILITY_POSITION_AND_STRING)
    #createInWorldText(getAllPlayers(), "91-92", Vectordoorpositions[45], 1, Clip.NONE, WorldTextReeval.VISIBILITY_POSITION_AND_STRING)
    #createInWorldText(getAllPlayers(), "93-94", Vectordoorpositions[46], 1, Clip.NONE, WorldTextReeval.VISIBILITY_POSITION_AND_STRING)
    #createInWorldText(getAllPlayers(), "95-96", Vectordoorpositions[47], 1, Clip.NONE, WorldTextReeval.VISIBILITY_POSITION_AND_STRING)
    #createInWorldText(getAllPlayers(), "97-98", Vectordoorpositions[48], 1, Clip.NONE, WorldTextReeval.VISIBILITY_POSITION_AND_STRING)
    #createInWorldText(getAllPlayers(), "99-100", Vectordoorpositions[49], 1, Clip.NONE, WorldTextReeval.VISIBILITY_POSITION_AND_STRING)
    #createInWorldText(getAllPlayers(), "101-102", Vectordoorpositions[50], 1, Clip.NONE, WorldTextReeval.VISIBILITY_POSITION_AND_STRING)
    #createInWorldText(getAllPlayers(), "103-104", Vectordoorpositions[51], 1, Clip.NONE, WorldTextReeval.VISIBILITY_POSITION_AND_STRING)
    #createInWorldText(getAllPlayers(), "105-106", Vectordoorpositions[52], 1, Clip.NONE, WorldTextReeval.VISIBILITY_POSITION_AND_STRING)
    #createInWorldText(getAllPlayers(), "107-108", Vectordoorpositions[53], 1, Clip.NONE, WorldTextReeval.VISIBILITY_POSITION_AND_STRING)
    #createInWorldText(getAllPlayers(), "109-110", Vectordoorpositions[54], 1, Clip.NONE, WorldTextReeval.VISIBILITY_POSITION_AND_STRING)
    #createInWorldText(getAllPlayers(), "111-112", Vectordoorpositions[55], 1, Clip.NONE, WorldTextReeval.VISIBILITY_POSITION_AND_STRING)
    #createInWorldText(getAllPlayers(), "113-114", Vectordoorpositions[56], 1, Clip.NONE, WorldTextReeval.VISIBILITY_POSITION_AND_STRING)
    #createInWorldText(getAllPlayers(), "115-116", Vectordoorpositions[57], 1, Clip.NONE, WorldTextReeval.VISIBILITY_POSITION_AND_STRING)
    #createInWorldText(getAllPlayers(), "117-118", Vectordoorpositions[58], 1, Clip.NONE, WorldTextReeval.VISIBILITY_POSITION_AND_STRING)
    #createInWorldText(getAllPlayers(), "119-120", Vectordoorpositions[59], 1, Clip.NONE, WorldTextReeval.VISIBILITY_POSITION_AND_STRING)
    #createInWorldText(getAllPlayers(), "121-122", Vectordoorpositions[60], 1, Clip.NONE, WorldTextReeval.VISIBILITY_POSITION_AND_STRING)
    #createInWorldText(getAllPlayers(), "123-124", Vectordoorpositions[61], 1, Clip.NONE, WorldTextReeval.VISIBILITY_POSITION_AND_STRING)
    #createInWorldText(getAllPlayers(), "125-126", Vectordoorpositions[62], 1, Clip.NONE, WorldTextReeval.VISIBILITY_POSITION_AND_STRING)
    #createInWorldText(getAllPlayers(), "127-128", Vectordoorpositions[63], 1, Clip.NONE, WorldTextReeval.VISIBILITY_POSITION_AND_STRING)
    #createInWorldText(getAllPlayers(), "129-130", Vectordoorpositions[64], 1, Clip.NONE, WorldTextReeval.VISIBILITY_POSITION_AND_STRING)
    #createInWorldText(getAllPlayers(), "131-132", Vectordoorpositions[65], 1, Clip.NONE, WorldTextReeval.VISIBILITY_POSITION_AND_STRING)
    #createInWorldText(getAllPlayers(), "133-134", Vectordoorpositions[66], 1, Clip.NONE, WorldTextReeval.VISIBILITY_POSITION_AND_STRING)
    #createInWorldText(getAllPlayers(), "135-136", Vectordoorpositions[67], 1, Clip.NONE, WorldTextReeval.VISIBILITY_POSITION_AND_STRING)
    #createInWorldText(getAllPlayers(), "137-138", Vectordoorpositions[68], 1, Clip.NONE, WorldTextReeval.VISIBILITY_POSITION_AND_STRING)
    #createInWorldText(getAllPlayers(), "139-140", Vectordoorpositions[69], 1, Clip.NONE, WorldTextReeval.VISIBILITY_POSITION_AND_STRING)
    #createInWorldText(getAllPlayers(), "141-142", Vectordoorpositions[70], 1, Clip.NONE, WorldTextReeval.VISIBILITY_POSITION_AND_STRING)
    #createInWorldText(getAllPlayers(), "143-144", Vectordoorpositions[71], 1, Clip.NONE, WorldTextReeval.VISIBILITY_POSITION_AND_STRING)
    #createInWorldText(getAllPlayers(), "145-146", Vectordoorpositions[72], 1, Clip.NONE, WorldTextReeval.VISIBILITY_POSITION_AND_STRING)
    #createInWorldText(getAllPlayers(), "147-148", Vectordoorpositions[73], 1, Clip.NONE, WorldTextReeval.VISIBILITY_POSITION_AND_STRING)
    #createInWorldText(getAllPlayers(), "149-150", Vectordoorpositions[74], 1, Clip.NONE, WorldTextReeval.VISIBILITY_POSITION_AND_STRING)
    #createInWorldText(getAllPlayers(), "151-152", Vectordoorpositions[75], 1, Clip.NONE, WorldTextReeval.VISIBILITY_POSITION_AND_STRING)
    #createInWorldText(getAllPlayers(), "153-154", Vectordoorpositions[76], 1, Clip.NONE, WorldTextReeval.VISIBILITY_POSITION_AND_STRING)
    #createInWorldText(getAllPlayers(), "155-156", Vectordoorpositions[77], 1, Clip.NONE, WorldTextReeval.VISIBILITY_POSITION_AND_STRING)
    #createInWorldText(getAllPlayers(), "157-158", Vectordoorpositions[78], 1, Clip.NONE, WorldTextReeval.VISIBILITY_POSITION_AND_STRING)
    #createInWorldText(getAllPlayers(), "159-160", Vectordoorpositions[79], 1, Clip.NONE, WorldTextReeval.VISIBILITY_POSITION_AND_STRING)
    #createInWorldText(getAllPlayers(), "161-162", Vectordoorpositions[80], 1, Clip.NONE, WorldTextReeval.VISIBILITY_POSITION_AND_STRING)
    #overlaps
    #createInWorldText(getAllPlayers(), "163-164", Vectordoorpositions[81], 1, Clip.NONE, WorldTextReeval.VISIBILITY_POSITION_AND_STRING)
    #createInWorldText(getAllPlayers(), "165-166", Vectordoorpositions[82], 1, Clip.NONE, WorldTextReeval.VISIBILITY_POSITION_AND_STRING)
    #createInWorldText(getAllPlayers(), "167-168", Vectordoorpositions[83], 1, Clip.NONE, WorldTextReeval.VISIBILITY_POSITION_AND_STRING)
    #createInWorldText(getAllPlayers(), "169-170", Vectordoorpositions[84], 1, Clip.NONE, WorldTextReeval.VISIBILITY_POSITION_AND_STRING)
    #createInWorldText(getAllPlayers(), "171-172", Vectordoorpositions[85], 1, Clip.NONE, WorldTextReeval.VISIBILITY_POSITION_AND_STRING)
    #createInWorldText(getAllPlayers(), "173-174", Vectordoorpositions[86], 1, Clip.NONE, WorldTextReeval.VISIBILITY_POSITION_AND_STRING)


rule "use interact to give pack a punch (Dev testing)":
    @Event eachPlayer
    @Condition eventPlayer.isHoldingButton(Button.INTERACT) == true
    @Disabled
    
    eventPlayer.Packapunch = 1


rule "Dev Tool Show variables":
#hudText(hostPlayer, "{0} - {1} - {2}".format(getServerLoad(), getAverageServerLoad(), " {0} A {1} B {2}".format(getPeakServerLoad(), A, "{0} C {1} D {2}".format(B, C, " {0} E {1} F {2}".format(null, null, null)))), E, F, HudPosition.TOP, 0, Color.WHITE, Color.WHITE, Color.WHITE, HudReeval.VISIBILITY_AND_STRING)

rule "change waves":
    @Event eachPlayer
    @Condition eventPlayer.isHoldingButton(Button.INTERACT) == true
    @Disabled
    
    numberOfZombies = 1
    g += 1