/*
settings
{
	main
	{
		Description: "press workshop settings to load gamemode"
		Mode Name: "Zombies Antarctic Peninsula"
	}

	lobby
	{
		Allow Players Who Are In Queue: Yes
		Map Rotation: After A Game
		Max Spectators: 12
		Max Team 1 Players: 4
		Max Team 2 Players: 0
		Return To Lobby: Never
	}

	modes
	{
		disabled Assault
		{
			Allow Hero Switching: Disabled
			Enemy Health Bars: Disabled
			Game Mode Start: Immediately
			Hero Limit: Off
			Kill Cam: Disabled
			Kill Feed: Disabled
			Spawn Health Packs: Disabled
			Tank Role Passive Health Bonus: Disabled
		}

		disabled Capture the Flag
		{
			Allow Hero Switching: Disabled
			Enemy Health Bars: Disabled
			Game Mode Start: Immediately
			Hero Limit: Off
			Kill Cam: Disabled
			Kill Feed: Disabled
			Spawn Health Packs: Disabled
			Tank Role Passive Health Bonus: Disabled
		}

		Control
		{
			Allow Hero Switching: Disabled
			Capture Speed Modifier: 10%
			Enemy Health Bars: Disabled
			Game Mode Start: Immediately
			Hero Limit: Off
			Kill Cam: Disabled
			Kill Feed: Disabled
			Spawn Health Packs: Disabled
			Tank Role Passive Health Bonus: Disabled

			enabled maps
			{
				Antarctic Peninsula 972777519512068154
			}
		}

		disabled Control Balanced Overwatch
		{
			Allow Hero Switching: Disabled
			Enemy Health Bars: Disabled
			Game Mode Start: Immediately
			Hero Limit: Off
			Kill Cam: Disabled
			Kill Feed: Disabled
			Spawn Health Packs: Disabled
			Tank Role Passive Health Bonus: Disabled
		}

		disabled Deathmatch
		{
			Allow Hero Switching: Disabled
			Enemy Health Bars: Disabled
			Game Mode Start: Immediately
			Hero Limit: Off
			Kill Cam: Disabled
			Kill Feed: Disabled
			Spawn Health Packs: Disabled
			Tank Role Passive Health Bonus: Disabled
		}

		disabled Elimination
		{
			Allow Hero Switching: Disabled
			Enemy Health Bars: Disabled
			Game Mode Start: Immediately
			Hero Limit: Off
			Kill Cam: Disabled
			Kill Feed: Disabled
			Spawn Health Packs: Disabled
		}

		disabled Escort
		{
			Allow Hero Switching: Disabled
			Enemy Health Bars: Disabled
			Game Mode Start: Immediately
			Hero Limit: Off
			Kill Cam: Disabled
			Kill Feed: Disabled
			Spawn Health Packs: Disabled
			Tank Role Passive Health Bonus: Disabled
		}

		disabled Hybrid
		{
			Allow Hero Switching: Disabled
			Enemy Health Bars: Disabled
			Game Mode Start: Immediately
			Hero Limit: Off
			Kill Cam: Disabled
			Kill Feed: Disabled
			Spawn Health Packs: Disabled
			Tank Role Passive Health Bonus: Disabled
		}

		Skirmish
		{
			Allow Hero Switching: Disabled
			Enemy Health Bars: Disabled
			Game Mode Start: Immediately
			Hero Limit: Off
			Kill Cam: Disabled
			Kill Feed: Disabled
			Spawn Health Packs: Disabled
			Tank Role Passive Health Bonus: Disabled

			enabled maps
			{
			}
		}

		disabled Team Deathmatch
		{
			Allow Hero Switching: Disabled
			Enemy Health Bars: Disabled
			Game Mode Start: Immediately
			Hero Limit: Off
			Kill Cam: Disabled
			Kill Feed: Disabled
			Spawn Health Packs: Disabled
			Tank Role Passive Health Bonus: Disabled
		}
	}

	heroes
	{
		Team 1
		{
			Health: 40%
			Movement Speed: 115%

			Ana
			{
				Biotic Grenade Cooldown Time: 50%
				Damage Dealt: 300%
				Healing Dealt: 150%
				Sleep Dart Cooldown Time: 0%
			}

			Baptiste
			{
				Ammunition Clip Size Scalar: 50%
				Damage Dealt: 163%
				Healing Dealt: 150%
				Regenerative Burst Cooldown Time: 25%
				Spawn With Ultimate Ready: Enabled
			}

			Bastion
			{
				Health: 34%
				Reconfigure Cooldown Time: 0%
			}

			Brigitte
			{
				Barrier Shield Cooldown Time: 50%
				Damage Dealt: 70%
				Healing Dealt: 40%
				Health: 50%
				Repair Pack Cooldown Time: 50%
				Shield Bash Cooldown Time: 50%
				Shield Bash Knockback Scalar: 300%
				Whip Shot Cooldown Time: 50%
				Whip Shot Knockback Scalar: 300%
			}

			D.Va
			{
				Boosters Cooldown Time: 200%
				Damage Dealt: 20%
				Health: 26%
				Spawn Without Mech: Enabled
				Ultimate Ability Self-Destruct: Disabled
			}

			Doomfist
			{
				Damage Dealt: 60%
				Healing Received: 50%
				Health: 40%
				No Ammunition Requirement: On
				Power Block Cooldown Time: 50%
				Rocket Punch Cooldown Time: 50%
				Seismic Slam Cooldown Time: 50%
			}

			Echo
			{
				Damage Dealt: 200%
				Flight Cooldown Time: 500%
				Focusing Beam Cooldown Time: 50%
				Glide: Disabled
			}

			Genji
			{
				Damage Dealt: 40%
			}

			Junker Queen
			{
				Healing Received: 50%
				Health: 50%
				Projectile Speed: 15%
			}

			Kiriko
			{
				Damage Dealt: 150%
			}

			Lúcio
			{
				Healing Dealt: 250%
			}

			Mercy
			{
				Ammunition Clip Size Scalar: 50%
				Damage Dealt: 150%
				Healing Dealt: 150%
				Resurrect Cooldown Time: 0%
				Ultimate Generation - Combat Valkyrie: 0%
				Ultimate Generation - Passive Valkyrie: 0%
				Ultimate Generation Valkyrie: 10%
			}

			Moira
			{
				Biotic Orb Cooldown Time: 25%
				Damage Dealt: 150%
				Fade Cooldown Time: 200%
				Healing Dealt: 150%
				Health: 50%
			}

			Orisa
			{
				Damage Dealt: 20%
				Energy Javelin Cooldown Time: 50%
				Fortify Cooldown Time: 75%
				Healing Received: 50%
				Health: 32%
				Javelin Spin Cooldown Time: 25%
			}

			Ramattra
			{
				Healing Received: 50%
				Health: 40%
				Nemesis Form Cooldown Time: 0%
			}

			Reinhardt
			{
				Barrier Field Recharge Rate: 300%
				Charge Cooldown Time: 50%
				Charge Knockback Scalar: 300%
				Damage Dealt: 65%
				Fire Strike Cooldown Time: 10%
				Healing Received: 50%
				Health: 27%
				Ultimate Generation Earthshatter: 165%
			}

			Roadhog
			{
				Chain Hook Cooldown Time: 0%
				Damage Dealt: 105%
				Healing Received: 33%
				Health: 23%
			}

			Sigma
			{
				Accretion Knockback Scalar: 300%
				Damage Dealt: 420%
				Experimental Barrier Cooldown Time: 0%
				Experimental Barrier Recharge Rate: 300%
				Healing Received: 50%
				Health: 32%
			}

			Soldier: 76
			{
				Ammunition Clip Size Scalar: 82%
			}

			Sombra
			{
				Ammunition Clip Size Scalar: 150%
				Damage Dealt: 250%
				Hack Cooldown Time: 25%
				Projectile Speed: 10%
				Translocator Cooldown Time: 75%
				Virus Cooldown Time: 300%
			}

			Symmetra
			{
				Damage Dealt: 70%
				Sentry Turret Cooldown Time: 200%
				Spawn With Ultimate Ready: Enabled
			}

			Torbjörn
			{
				Damage Dealt: 70%
				Deploy Turret Cooldown Time: 25%
				Overload Cooldown Time: 40%
				Ultimate Generation Molten Core: 220%
			}

			Tracer
			{
				Damage Dealt: 260%
				Health: 67%
			}

			Winston
			{
				Barrier Projector Cooldown Time: 20%
				Damage Dealt: 70%
				Healing Received: 50%
				Health: 32%
				Jump Vertical Speed: 80%
				Primal Rage Melee Knockback Scalar: 300%
			}

			Wrecking Ball
			{
				Damage Dealt: 200%
				Grappling Claw Cooldown Time: 250%
				Healing Received: 50%
				Health: 24%
			}

			Zarya
			{
				Ammunition Clip Size Scalar: 200%
				Damage Dealt: 420%
				Healing Received: 50%
				Health: 38%
				Particle Barrier Cooldown Time: 40%
				Projected Barrier Cooldown Time: 40%
				Spawn With Ultimate Ready: Enabled
			}

			Zenyatta
			{
				Damage Dealt: 150%
				Healing Dealt: 150%
			}
		}

		Team 2
		{
			Health: 50%
			Movement Speed: 65%

			Ana
			{
				Biotic Grenade Cooldown Time: 50%
				Damage Dealt: 300%
				Healing Dealt: 150%
				Projectile Speed: 10%
				Sleep Dart Cooldown Time: 0%
			}

			Baptiste
			{
				Ammunition Clip Size Scalar: 50%
				Damage Dealt: 163%
				Healing Dealt: 150%
				Regenerative Burst Cooldown Time: 25%
			}

			Bastion
			{
				Ammunition Clip Size Scalar: 35%
				Damage Dealt: 20%
				Health: 34%
			}

			Brigitte
			{
				Barrier Shield Cooldown Time: 50%
				Damage Dealt: 70%
				Healing Dealt: 40%
				Health: 50%
				Repair Pack Cooldown Time: 50%
				Ultimate Generation - Combat Rally: 500%
				Ultimate Generation Rally: 500%
			}

			D.Va
			{
				Boosters Cooldown Time: 200%
				Damage Dealt: 20%
				Healing Received: 50%
				Health: 26%
				Movement Speed: 50%
				Ultimate Ability Self-Destruct: Disabled
			}

			Doomfist
			{
				Damage Dealt: 60%
				Healing Received: 50%
				Health: 250%
				No Ammunition Requirement: On
				Power Block Cooldown Time: 50%
				Rocket Punch Cooldown Time: 50%
				Seismic Slam Cooldown Time: 50%
			}

			Echo
			{
				Flight Cooldown Time: 500%
				Focusing Beam Cooldown Time: 50%
			}

			Genji
			{
				Damage Dealt: 40%
				Health: 50%
			}

			Junker Queen
			{
				Healing Received: 50%
				Health: 50%
				Movement Speed: 60%
				Projectile Gravity: 0%
				Projectile Speed: 15%
			}

			Kiriko
			{
				Projectile Speed: 0%
			}

			Lúcio
			{
				Ammunition Clip Size Scalar: 300%
				Damage Dealt: 500%
				Healing Dealt: 250%
				Soundwave Cooldown Time: 200%
			}

			Mercy
			{
				Ammunition Clip Size Scalar: 50%
				Damage Dealt: 150%
				Healing Dealt: 150%
				Movement Speed: 50%
				Resurrect Cooldown Time: 0%
				Ultimate Generation - Combat Valkyrie: 0%
				Ultimate Generation - Passive Valkyrie: 0%
				Ultimate Generation Valkyrie: 10%
				Weapons Enabled: Caduceus Blaster Only
			}

			Moira
			{
				Biotic Orb: Disabled
				Damage Dealt: 150%
				Fade Cooldown Time: 0%
				Healing Dealt: 150%
				Health: 50%
				Primary Fire: Disabled
				Secondary Fire: Disabled
				Ultimate Ability Coalescence: Disabled
			}

			Orisa
			{
				Damage Dealt: 20%
				Energy Javelin Cooldown Time: 50%
				Fortify Cooldown Time: 75%
				Healing Received: 50%
				Health: 34%
				Javelin Spin Cooldown Time: 25%
				Movement Speed: 50%
				Projectile Gravity: 0%
				Projectile Speed: 10%
			}

			Ramattra
			{
				Healing Received: 50%
				Health: 50%
				Nemesis Form Cooldown Time: 0%
			}

			Reinhardt
			{
				Barrier Field Recharge Rate: 300%
				Damage Dealt: 65%
				Fire Strike Cooldown Time: 10%
				Healing Received: 250%
				Health: 25%
				Rocket Hammer Knockback Scalar: 200%
				Ultimate Generation - Combat Earthshatter: 500%
				Ultimate Generation Earthshatter: 165%
			}

			Roadhog
			{
				Chain Hook Cooldown Time: 0%
				Damage Dealt: 50%
				Healing Received: 33%
				Health: 20%
			}

			Sigma
			{
				Accretion Cooldown Time: 25%
				Accretion Knockback Scalar: 300%
				Damage Dealt: 420%
				Experimental Barrier Cooldown Time: 0%
				Experimental Barrier Recharge Rate: 300%
				Healing Received: 50%
				Health: 38%
				Kinetic Grasp Cooldown Time: 0%
			}

			Soldier: 76
			{
				Ammunition Clip Size Scalar: 82%
				Projectile Speed: 25%
			}

			Sombra
			{
				Ammunition Clip Size Scalar: 150%
				Damage Dealt: 200%
				Hack Cooldown Time: 25%
				Projectile Speed: 10%
				Translocator Cooldown Time: 75%
				Virus Cooldown Time: 300%
			}

			Symmetra
			{
				Damage Dealt: 70%
				Sentry Turret Cooldown Time: 200%
			}

			Torbjörn
			{
				Damage Dealt: 70%
				Deploy Turret: Disabled
				Health: 50%
				Movement Gravity: 80%
				Overload Cooldown Time: 40%
				Overload Duration Scalar: 500%
				Ultimate Generation - Combat Molten Core: 500%
				Ultimate Generation Molten Core: 220%
				Weapons Enabled: Forge Hammer Only
			}

			Tracer
			{
				Ammunition Clip Size Scalar: 200%
				Damage Dealt: 160%
				Health: 67%
			}

			Winston
			{
				Ammunition Clip Size Scalar: 25%
				Barrier Projector: Disabled
				Damage Dealt: 70%
				Healing Received: 50%
				Health: 10%
				Jump Pack: Disabled
				Jump Pack Knockback Scalar: 400%
				Jump Vertical Speed: 80%
				Primal Rage Melee Knockback Scalar: 25%
				Ultimate Duration: 500%
			}

			Wrecking Ball
			{
				Damage Dealt: 200%
				Grappling Claw Cooldown Time: 250%
				Healing Received: 50%
				Health: 25%
				Movement Speed: 50%
			}

			Zarya
			{
				Ammunition Clip Size Scalar: 200%
				Damage Dealt: 420%
				Healing Received: 50%
				Health: 38%
				Particle Barrier Cooldown Time: 40%
				Projected Barrier Cooldown Time: 40%
			}

			Zenyatta
			{
				Damage Dealt: 150%
				Healing Dealt: 150%
				Health: 250%
			}
		}

		General
		{
			Passive Health Regeneration: Disabled
			Ultimate Generation: 10%
			Ultimate Generation - Combat: 0%
			Ultimate Generation - Passive: 0%

			Ashe
			{
				Coach Gun Cooldown Time: 35%
				Damage Dealt: 125%
				Dynamite Cooldown Time: 50%
			}

			Cassidy
			{
				Combat Roll Cooldown Time: 35%
				Damage Dealt: 30%
				Flashbang Cooldown Time: 15%
				Health: 45%
				Ultimate Ability Deadeye: Disabled
			}

			Hanzo
			{
				Damage Dealt: 300%
				Sonic Arrow Cooldown Time: 50%
				Storm Arrows Cooldown Time: 50%
				Storm Arrows Quantity: 6
			}

			Junkrat
			{
				Concussion Mine Cooldown Time: 50%
				Concussion Mine Knockback Scalar: 25%
				Damage Dealt: 250%
				Frag Launcher Knockback Scalar: 25%
				Steel Trap Cooldown Time: 25%
				Ultimate Duration: 25%
			}

			Mauga
			{
				Health: 26%
			}

			Mei
			{
				Ammunition Clip Size Scalar: 300%
				Cryo-Freeze Cooldown Time: 75%
				Damage Dealt: 500%
				Freeze Stacking: Enabled
				Health: 40%
				Ice Wall Cooldown Time: 25%
				Weapon Freeze Minimum: 100%
			}

			Pharah
			{
				Ammunition Clip Size Scalar: 200%
				Concussive Blast Cooldown Time: 50%
				Damage Dealt: 250%
				Hover Jets Recharge Rate: 5%
				Jump Jet Cooldown Time: 300%
			}

			Reaper
			{
				Shadow Step Cooldown Time: 50%
			}

			Widowmaker
			{
				Damage Dealt: 500%
				Grappling Hook Cooldown Time: 35%
				Health: 58%
				Venom Mine Cooldown Time: 0%
			}

			enabled heroes
			{
				Brigitte
				Doomfist
				Genji
				Moira
				Reinhardt
				Roadhog
				Torbjörn
				Winston
				Zenyatta
			}
		}
	}

	workshop
	{
		difficulty: 3
		gravity: 100.000
		zombie reaction time: 0.400
	}

	extensions
	{
		Beam Effects
		Buff Status Effects
		Debuff Status Effects
		Energy Explosion Effects
		Kinetic Explosion Effects
		Explosion Sounds
		Play More Effects
		Spawn More Dummy Bots
		Projectiles
	}
}

*/